// Per-resource configuration that drives the generic ResourcePage.
// field types: text, number, date, textarea, select (options), remote (endpoint), file

const PAYMENT_MODES = ['cash', 'bank_transfer', 'upi', 'cheque', 'card', 'other']

const company = { name: 'company_id', label: 'Company', type: 'remote', endpoint: '/companies', optionLabel: 'name', required: true, filter: true }

export const resources = {
  companies: {
    path: 'companies',
    title: 'Companies',
    endpoint: '/companies',
    idLabel: 'name',
    columns: [
      ['name', 'Name'],
      ['type', 'Type'],
      ['gstin', 'GSTIN'],
      ['phone', 'Phone'],
      ['currency', 'Currency'],
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'legal_name', label: 'Legal Name', type: 'text' },
      { name: 'type', label: 'Type', type: 'select', options: ['private_limited','sole_proprietorship','partnership','llp','other'] },
      { name: 'gstin', label: 'GSTIN', type: 'text' },
      { name: 'pan', label: 'PAN', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'currency', label: 'Currency', type: 'text', default: 'INR' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },

  clients: {
    path: 'clients',
    title: 'Clients',
    endpoint: '/clients',
    idLabel: 'name',
    columns: [['name','Name'],['contact_person','Contact'],['email','Email'],['phone','Phone']],
    fields: [
      company,
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'contact_person', label: 'Contact Person', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'gstin', label: 'GSTIN', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  vendors: {
    path: 'vendors',
    title: 'Vendors',
    endpoint: '/vendors',
    idLabel: 'name',
    columns: [['name','Name'],['contact_person','Contact'],['email','Email'],['phone','Phone']],
    fields: [
      company,
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'contact_person', label: 'Contact Person', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'gstin', label: 'GSTIN', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'expense-categories': {
    path: 'expense-categories',
    title: 'Expense Categories',
    endpoint: '/expense-categories',
    idLabel: 'name',
    columns: [['name','Name'],['slug','Slug']],
    fields: [
      { name: 'company_id', label: 'Company', type: 'remote', endpoint: '/companies', optionLabel: 'name' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },

  incomes: {
    path: 'incomes',
    title: 'Income',
    endpoint: '/incomes',
    columns: [
      ['invoice_no','Invoice'],
      ['client', 'Client', (r) => r.client?.name],
      ['total_amount','Total','money'],
      ['received_amount','Received','money'],
      ['pending_amount','Pending','money'],
      ['status','Status','badge'],
      ['due_date','Due'],
    ],
    statusFilter: ['paid','partial','pending','overdue'],
    addPayment: true,
    fields: [
      company,
      { name: 'client_id', label: 'Client', type: 'remote', endpoint: '/clients', optionLabel: 'name' },
      { name: 'invoice_no', label: 'Invoice No', type: 'text' },
      { name: 'project', label: 'Project / Service', type: 'text' },
      { name: 'total_amount', label: 'Total Amount', type: 'number', required: true },
      { name: 'received_amount', label: 'Received Amount', type: 'number' },
      { name: 'payment_date', label: 'Payment Date', type: 'date' },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'payment_mode', label: 'Payment Mode', type: 'select', options: PAYMENT_MODES },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  expenses: {
    path: 'expenses',
    title: 'Expenses',
    endpoint: '/expenses',
    multipart: true,
    columns: [
      ['expense_date','Date'],
      ['category','Category', (r) => r.category?.name],
      ['vendor','Vendor', (r) => r.vendor?.name],
      ['amount','Amount','money'],
      ['gst_amount','GST','money'],
      ['payment_mode','Mode'],
    ],
    fields: [
      company,
      { name: 'expense_category_id', label: 'Category', type: 'remote', endpoint: '/expense-categories', optionLabel: 'name' },
      { name: 'vendor_id', label: 'Vendor', type: 'remote', endpoint: '/vendors', optionLabel: 'name' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'gst_amount', label: 'GST Amount', type: 'number' },
      { name: 'expense_date', label: 'Date', type: 'date', required: true },
      { name: 'payment_mode', label: 'Payment Mode', type: 'select', options: PAYMENT_MODES },
      { name: 'bill', label: 'Bill (pdf/jpg/png)', type: 'file' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  receivables: {
    path: 'receivables',
    title: 'Receivables',
    endpoint: '/receivables',
    statusFilter: ['pending','partial','paid','overdue'],
    columns: [
      ['title','Title'],
      ['client','Client', (r) => r.client?.name],
      ['invoice_amount','Invoice','money'],
      ['received_amount','Received','money'],
      ['pending_amount','Pending','money'],
      ['status','Status','badge'],
      ['due_date','Due'],
    ],
    fields: [
      company,
      { name: 'client_id', label: 'Client', type: 'remote', endpoint: '/clients', optionLabel: 'name' },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'invoice_amount', label: 'Invoice Amount', type: 'number', required: true },
      { name: 'received_amount', label: 'Received Amount', type: 'number' },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'follow_up_date', label: 'Follow-up Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['pending','partial','paid','overdue'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  payables: {
    path: 'payables',
    title: 'Payables',
    endpoint: '/payables',
    statusFilter: ['pending','partial','paid','overdue'],
    columns: [
      ['title','Title'],
      ['type','Type'],
      ['vendor','Vendor', (r) => r.vendor?.name],
      ['amount','Amount','money'],
      ['paid_amount','Paid','money'],
      ['pending_amount','Pending','money'],
      ['status','Status','badge'],
      ['due_date','Due'],
    ],
    fields: [
      company,
      { name: 'vendor_id', label: 'Vendor', type: 'remote', endpoint: '/vendors', optionLabel: 'name' },
      { name: 'expense_category_id', label: 'Category', type: 'remote', endpoint: '/expense-categories', optionLabel: 'name' },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: ['salary','hosting','domain','vendor','gst','utility','other'] },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'paid_amount', label: 'Paid Amount', type: 'number' },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['pending','partial','paid','overdue'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'recurring-expenses': {
    path: 'recurring-expenses',
    title: 'Recurring Expenses',
    endpoint: '/recurring-expenses',
    columns: [
      ['title','Title'],
      ['amount','Amount','money'],
      ['frequency','Frequency'],
      ['next_run_date','Next Run'],
      ['is_active','Active', (r) => (r.is_active ? 'Yes' : 'No')],
    ],
    fields: [
      company,
      { name: 'expense_category_id', label: 'Category', type: 'remote', endpoint: '/expense-categories', optionLabel: 'name' },
      { name: 'vendor_id', label: 'Vendor', type: 'remote', endpoint: '/vendors', optionLabel: 'name' },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'gst_amount', label: 'GST Amount', type: 'number' },
      { name: 'frequency', label: 'Frequency', type: 'select', options: ['daily','weekly','monthly','quarterly','yearly'], required: true },
      { name: 'day_of_month', label: 'Day of Month', type: 'number' },
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'next_run_date', label: 'Next Run Date', type: 'date' },
      { name: 'payment_mode', label: 'Payment Mode', type: 'select', options: PAYMENT_MODES },
    ],
  },

  reminders: {
    path: 'reminders',
    title: 'Reminders',
    endpoint: '/reminders',
    statusFilter: ['pending','sent','dismissed'],
    columns: [
      ['title','Title'],
      ['type','Type'],
      ['remind_at','Remind At'],
      ['status','Status','badge'],
    ],
    fields: [
      company,
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'message', label: 'Message', type: 'textarea' },
      { name: 'type', label: 'Type', type: 'select', options: ['payment_due','invoice_overdue','domain_expiry','hosting_renewal','custom'] },
      { name: 'remind_at', label: 'Remind At', type: 'date', required: true },
    ],
  },
}
